[workspace]
members = [
        "prover",
        "polyglot",
        "jit",
        "common",
]
exclude = [
        "polyglot/fuzz",
        "polyglot/honggfuzz",
        "polyglot/programs/sha3",
]

[profile.release]
debug = true
