[workspace]
members = [
        "arbutil",
        "prover",
        "stylus",
        "jit",
        "seraphina-runner",
        "gas-pricer",
]
exclude = [
        "stylus/tests/"
]

[profile.release]
debug = true
