[package]
name = "poly-host"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
arbutil = { path = "../../arbutil/" }
wavm-util = { path = "../wavm-util/" }
hashbrown = "0.12.3"
hex = "0.4.3"
